# install.ps1 — GitHub Copilot adapter for excalidraw-skill-pack
# Writes to the CURRENT directory (project-scoped instructions).
# Usage:  $env:ESP_CORE_DIR = "<path>"; .\install.ps1 [full|lite]
param([string]$Mode = "full")

$ErrorActionPreference = "Stop"

if ($env:ESP_CORE_DIR -and (Test-Path (Join-Path $env:ESP_CORE_DIR "SKILL.md"))) {
    $CoreDir = $env:ESP_CORE_DIR
} else {
    $corePkg = node -e "console.log(require.resolve('@excalidraw-skill-pack/core/skill'))" 2>$null
    if (-not $corePkg) { throw "Cannot locate @excalidraw-skill-pack/core" }
    $CoreDir = Split-Path $corePkg
}

$CopilotDir  = ".github"
$CopilotFile = Join-Path $CopilotDir "copilot-instructions.md"
$VsCodeDir   = ".vscode"
$McpFile     = Join-Path $VsCodeDir "mcp.json"

Write-Host "excalidraw-skill-pack > copilot adapter"
Write-Host "  mode:   $Mode"
Write-Host "  target: $(Get-Location)\$CopilotFile"
Write-Host ""

New-Item -ItemType Directory -Force -Path $CopilotDir | Out-Null

$skillContent = Get-Content (Join-Path $CoreDir "SKILL.md") -Raw
if ($skillContent -match '(?ms)^---.*?^---\r?\n(.*)') {
    $skillBody = $Matches[1]
} else {
    $skillBody = $skillContent
}

$header = "<!-- generated by @excalidraw-skill-pack/install copilot — do not edit by hand -->`n"
Set-Content -Path $CopilotFile -Value ($header + $skillBody) -NoNewline

Write-Host "  OK  $CopilotFile written"

if ($Mode -eq "full") {
    New-Item -ItemType Directory -Force -Path $VsCodeDir | Out-Null

    if (Test-Path $McpFile) {
        $cfg = Get-Content $McpFile -Raw | ConvertFrom-Json
    } else {
        $cfg = [PSCustomObject]@{ servers = [PSCustomObject]@{} }
    }

    $cfg.servers | Add-Member -Force -NotePropertyName "excalidraw-skill-pack" -NotePropertyValue ([PSCustomObject]@{
        type    = "stdio"
        command = "npx"
        args    = @("@excalidraw-skill-pack/mcp-server")
    })

    $cfg | ConvertTo-Json -Depth 10 | Set-Content $McpFile
    Write-Host "  OK  MCP server registered in $McpFile"
}

Write-Host ""
Write-Host "Done. Open GitHub Copilot Chat in VS Code — the skill is now in context."
