#!/usr/bin/env bash
# install.sh — GitHub Copilot adapter for excalidraw-skill-pack
# Writes to the CURRENT directory (project-scoped instructions).
# Usage:  ESP_CORE_DIR=<path> bash install.sh [full|lite]
set -euo pipefail

MODE="${1:-full}"

if [ -n "${ESP_CORE_DIR:-}" ] && [ -f "$ESP_CORE_DIR/SKILL.md" ]; then
  CORE_DIR="$ESP_CORE_DIR"
else
  CORE_PKG_DIR=$(node -e "console.log(require.resolve('@excalidraw-skill-pack/core/skill'))" 2>/dev/null || true)
  if [ -z "$CORE_PKG_DIR" ]; then
    echo "ERROR: cannot locate @excalidraw-skill-pack/core. Run via 'npx @excalidraw-skill-pack/install' or install core globally first." >&2
    exit 1
  fi
  CORE_DIR=$(dirname "$CORE_PKG_DIR")
fi

COPILOT_DIR=".github"
COPILOT_FILE="$COPILOT_DIR/copilot-instructions.md"
VSCODE_DIR=".vscode"
MCP_FILE="$VSCODE_DIR/mcp.json"

echo "excalidraw-skill-pack › copilot adapter"
echo "  mode:   $MODE"
echo "  target: $(pwd)/$COPILOT_FILE"
echo ""

# ── write .github/copilot-instructions.md ────────────────────────────────────
mkdir -p "$COPILOT_DIR"

SKILL_BODY=$(awk '
  /^---$/ && !seen { seen=1; in_front=1; next }
  in_front && /^---$/ { in_front=0; next }
  !in_front { print }
' "$CORE_DIR/SKILL.md")

cat > "$COPILOT_FILE" <<EOF
<!-- generated by @excalidraw-skill-pack/install copilot — do not edit by hand -->
$SKILL_BODY
EOF

echo "  ✓  $COPILOT_FILE written"

# ── full mode: register MCP server in .vscode/mcp.json ───────────────────────
if [ "$MODE" = "full" ]; then
  mkdir -p "$VSCODE_DIR"

  if [ -f "$MCP_FILE" ]; then
    EXISTING=$(cat "$MCP_FILE")
    UPDATED=$(node -e "
      const cfg = JSON.parse(process.argv[1]);
      cfg.servers = cfg.servers || {};
      cfg.servers['excalidraw-skill-pack'] = {
        type: 'stdio',
        command: 'npx',
        args: ['@excalidraw-skill-pack/mcp-server']
      };
      process.stdout.write(JSON.stringify(cfg, null, 2));
    " "$EXISTING")
    printf '%s\n' "$UPDATED" > "$MCP_FILE"
  else
    cat > "$MCP_FILE" <<'JSON'
{
  "servers": {
    "excalidraw-skill-pack": {
      "type": "stdio",
      "command": "npx",
      "args": ["@excalidraw-skill-pack/mcp-server"]
    }
  }
}
JSON
  fi
  echo "  ✓  MCP server registered in $MCP_FILE"
fi

echo ""
echo "Done. Open GitHub Copilot Chat in VS Code — the skill is now in context."
if [ "$MODE" = "lite" ]; then
  echo "  (lite mode — MCP server not registered)"
fi
